# LA

In [2]:
# importing all the required libraries
import torch
import tensorflow as tf
import numpy as np

In [3]:
# calculating the norm
a  = np.array([1, 2, 3])

norm_manual = (a[0]**2 + a[1]**2 + a[2]**2)**0.5
print("Manual norm:", norm_manual)

norm_numpy = np.linalg.norm(a)
print("NumPy norm:", norm_numpy)

Manual norm: 3.7416573867739413
NumPy norm: 3.7416573867739413


In [6]:
# check the orthogonal 
a = np.array([1, 0])
b = np.array([0, 1])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)  
a@b

Dot product: 0


np.int64(0)

In [12]:
# matrix tensors
X = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy array:\n", X)

print("Shape:", X.shape)
print("Data type:", X.dtype)
print("Number of dimensions:", X.ndim)
print("Size:", X.size)

NumPy array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data type: int64
Number of dimensions: 2
Size: 6


In [13]:
# working with pytorch
X_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("PyTorch tensor:\n", X_pt)

print("Shape:", X_pt.shape)
print("Data type:", X_pt.dtype)
print("Number of dimensions:", X_pt.ndim)
print("Size:", X_pt.numel())

PyTorch tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Data type: torch.int64
Number of dimensions: 2
Size: 6


In [16]:
# working with tensor flow
X_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
print("TensorFlow variable:\n", X_tf)

print("Shape:", X_tf.shape)
print("Data type:", X_tf.dtype)



TensorFlow variable:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
Shape: (2, 3)
Data type: <dtype: 'int32'>


In [ ]:
# higher order tensor (order 4)
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [20]:
images_tf = tf.zeros([32, 28, 28, 3])
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

In [21]:
# calculation of hadamard product
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = a * b
c

tensor([[ 5, 12],
        [21, 32]])